### ISSUE TITLE
[on hold] shared-libs - PxCs.dll needs a dynamic way to pick correlated phoenix-shared.dll/.so/.arm.so based on target architecture

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/unZENity-VR#39]
Currently we have 3 libphoenix-shared.* files:
* .dll -> for windows builds
* .so -> for Linux builds (for development)
* .so -> for Arm builds (Pico4/Quest2)

We need to have a way to let the PxCs.dll select the right libphoenix-shared.* file based on currently running target architecture.

Some ideas:
1. Symlink the right .so inside Unity package (before packaging?)
2. Add precompiler directive on DLLNAME within PxCs.dll
3. Add a method to instanciate the value within PxCs.dll (e.g. _SetTargetArchitecture()_ --> sets the right _DllImport()_
4. Add prebuild step where it renames the arm .so [rename file](https://docs.unity3d.com/ScriptReference/AssetDatabase.RenameAsset.html) within step [prebuild script exec](https://docs.unity3d.com/ScriptReference/Build.IPreprocessBuildWithReport.OnPreprocessBuild.html) and [example build](https://forum.unity.com/threads/excluding-folders-from-build.408375/page-2)

**Comment by JaXt0r** [comment]
Let's got with the prebuild/postbuild idea within unity.

There are (or will be created) 3 shared libraries within Assets/unZENity-VR/Dependencies.

One Todo: We need to rename the *libphoenix-shared.arm.so* during Bild to *libphoenix-shared.so* to be found by PxCs.dll during runtime on Android.

**Comment by Tyroonis** [comment]
https://forum.unity.com/threads/excluding-folders-from-build.408375/page-2

**Comment by JaXt0r** [comment]
Bonus: it would be great if we can rename the files back to normal within postprocess. Otherwise they might be shown as git change afaik. 😉

**Comment by JaXt0r** [comment]
Currently in discussions if we need the .so for linux at all as there is no way of developing/playing with OpenXR plugin on Linux. > Ticket is ON_HOLD.

**Comment by JaXt0r** [comment]
Discussed with team and fixed: libphoenix-shared.so is for arm, lipbhoenix-shared.dll is for windows and libphoenix-shared.linux.so is for linux (and needs to be renamed before developing on linux).
